# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "d56fae01af1332ad0f35a3bbc61bfd72a8873449bbb99b9389987ff235de1a0a"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7baa0a42e54bfcb95e540b7747c22fd20a8d835c0f98cf547a7005e23269d730"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6fe7a457f4f2f727e1dfe74f266c4fb2388732a15c1a99ce1434c036873f8d5b"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cbe5a84a8526884854fce2f37018e4b713b321ec497b9c3a6aec2b49f3cb4ae4"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
    end
  end

  name "lazyworktree"
  desc "A TUI for managing git worktrees"
  homepage "https://github.com/dev-shimada/lazyworktree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"

  # No zap stanza required

end
