# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "3b30f938cc0e7c187bddfca078c0706f71a15532c929999f4347e027f7ed195b"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "29abfaf32451beb274c0bd94e708c53408342eb38d19c953d50ca4f53bf103e9"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee4d304c9b853dad4ebd61be33db809adff7c57fb2388ebc508ed91d1eb9453c"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2c3c6f69c2e292463ee41217e4dbb6c20e21aabbcd3baf9e202fca6e946984f7"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
    end
  end

  name "lazyworktree"
  desc "A TUI for managing git worktrees"
  homepage "https://github.com/dev-shimada/lazyworktree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"

  # No zap stanza required

end
