# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  version "0.0.6"

  on_macos do
    on_arm do
      sha256 "5fc6eec50de9b9de47a4197d75c4140a022e5ea05bc07edb538745200cee031d"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "633f84b2fc8d14fd4ae1fe60a7ea1b66d09354432ade17d7ccdca576d1fdc14c"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "832770bba7b294c17ac590d72377a22e7117c560b21cac3de7544f19a94a9e8b"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d2dad8d8a4a97fbc86a881a37bce5c9016e37c255e3661bece7965d915abdd5a"
      url "https://github.com/dev-shimada/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
    end
  end

  name "lazyworktree"
  desc "A TUI for managing git worktrees"
  homepage "https://github.com/dev-shimada/lazyworktree"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"

  # No zap stanza required
end
